### ISSUE TITLE
client.send() does not receive

### ISSUE THREAD

**Issue by leopoldodonnell** [alexy4744/packages#1]
While attempting to use the NATS JetStream Transporter, the `NatsClient` send method does not return/receive a response from a value returned from `@MessagePattern()`.

I would love to use this package as it would help us a ton, the consumer/event side works great! but we're stuck with the Message pattern...

The service will print the following output and no more when accessed via `http://localhost:3000`:

```
[Nest] ...
 >> jetstream functionality in nats.js is preview functionality 
[Nest] 25247   - 08/03/2021, 4:53:52 PM   [NatsServer] Subscribed to hello.> events
[Nest] 25247   - 08/03/2021, 4:53:52 PM   [NatsServer] Subscribed to {"cmd":"sayHi"} messages
[Nest] 25247   - 08/03/2021, 4:53:52 PM   [NatsServer] Connected to 127.0.0.1:4222
[Nest] 25247   - 08/03/2021, 4:53:52 PM   [RoutesResolver] AppController {}: +5ms
[Nest] 25247   - 08/03/2021, 4:53:52 PM   [RouterExplorer] Mapped {, GET} route +3ms
[Nest] 25247   - 08/03/2021, 4:53:52 PM   [NestApplication] Nest application successfully started +2ms
[Nest] 25247   - 08/03/2021, 4:53:52 PM   Listening +4ms
getHello
[Nest] 25247   - 08/03/2021, 4:55:04 PM   [NatsClient] Connected to 127.0.0.1:4222
sayHi  Leo
TAPPED undefined

```
The expectation is that it would also print `Hi Leo` - am I missing something?

```typescript
import { Controller, Get } from '@nestjs/common'
import { AppService } from './app.service'
import { EventPattern, Payload, Ctx, MessagePattern } from '@nestjs/microservices'
import { NatsContext, NatsClient } from '@alexy4744/nestjs-nats-jetstream-transporter'
import { Observable } from 'rxjs'
import { tap } from 'rxjs/operators'
import { StringCodec } from 'nats'

@Controller()
export class AppController {
  private readonly client = new NatsClient({ codec: StringCodec() })

  constructor(private readonly appService: AppService) {}

  @Get()
  getHello(): Observable<string> {
    console.log('getHello')
    const value = this.client.send<string>({ cmd: 'sayHi' }, 'Leo').pipe(
      tap((obj) => {
        console.log('TAPPED', obj)
      }),
    )
    return value
  }

  @EventPattern('hello.>')
  handleHello(@Payload() data: string, @Ctx() context: NatsContext): void {
    console.log(data)
    console.log(context)
  }

  @MessagePattern({ cmd: 'sayHi' })
  sayHi(@Payload() data: string): string {
    console.log('sayHi ', data)
    return `Hi ${data}`
  }
}
```

**Comment by alexy4744** [comment]
I figured out the problem. NestJS sends objects containing the pattern and message data, and when this object gets encoded using `StringCodec`, it returns `[object Object]`, which isn't correct. I'm not sure what my thought process was, but the codec should always be `JSONCodec()` because your actual message payload is internally wrapped within an object by NestJS

So the solution to this is to remove the `{ codec: StringCodec() }` from both the transport strategy and the NATS client. I will make a PR soon that will remove the `codec` option entirely.

Let me know if this fixes your issue.

**Comment by alexy4744** [comment]
After a second thought, I'm thinking to keep the codec option just in case if someone in the future wants to implement their own codec to transform payloads before encoding and after decoding.

**Comment by leopoldodonnell** [comment]
Thank you for taking a look so quickly.

Your reasoning sounds good, but I've tried removing and then swapping the codec for the JSON codec and it fails with

```
[Nest] 36812   - 08/04/2021, 11:25:49 AM   [ExceptionsHandler] Bad JSON +21ms
NatsError: Bad JSON
    at Function.errorForCode (/Users/leoodonnell/dev/wiser/event-store/dp-event-analysis/nats-nest/node_modules/nats/nats-base-client/error.ts:115:12)
    at Object.decode (/Users/leoodonnell/dev/wiser/event-store/dp-event-analysis/nats-nest/node_modules/nats/nats-base-client/codec.ts:53:25)
    at /Users/leoodonnell/dev/wiser/event-store/dp-event-analysis/nats-nest/packages/nestjs-nats-jetstream-transporter/src/lib/nats.client.ts:124:37
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I've run two services to ensure that the HTTP request in one service makes the NATS request that is serviced by the other.

Later on today I'm going to try the MessagePatten with vanilla NATS, to validate that it should work, in principle.

**Comment by leopoldodonnell** [comment]
Ugh - I misunderstood - I removed the StringCodec in both places and now everything works!
