### ISSUE TITLE
Changes to config not documented?

### ISSUE THREAD

**Issue by peregrinator** [alexy4744/packages#10]
In this commit, a68da987, it appears that the `streams` key was removed from the transport config. However the documentation hasn't been updated.

What is the expected config at this point?
Thanks!

**Comment by alexy4744** [comment]
Hey, these changes are not yet published to npm, they are part of a new release that I planned but didn't have the time to finish. The plan was to make the library more flexible by allowing developers to configure JetStream and message consumers on a global, and per-handler level and also remove automatic upsert of streams as streams should really be created and configured on the NATS level, not in application code.

So the documentation you are currently seeing correctly reflects with the version on npm.

**Comment by peregrinator** [comment]
I see, that's helpful context! Appreciate the quick reply.
